/* Actual Chromium UI, synthetic models and mocked bridge; no user configuration. */
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(__dirname,'..'),web=path.join(root,'web');
const source=fs.readFileSync(path.join(__dirname,'test_ui_preferences.cjs'),'utf8').replace(/\r\n/g,'\n');
const begin=source.indexOf('await page.addInitScript(')+'await page.addInitScript('.length,end=source.indexOf('\n    });\n    const url',begin)+6,init=eval('('+source.slice(begin,end)+')');
const server=http.createServer((req,res)=>{
 const url=new URL(req.url,'http://localhost'),p=path.resolve(web,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));
 if(!p.startsWith(web+path.sep)){res.writeHead(403).end();return;}
 fs.readFile(p,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':'text/html; charset=utf-8');res.end(b);});
});
let passed=0;function ok(s){console.log('OK '+s);passed++;}
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(init);await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.__ready&&document.querySelector('#settingsForm [data-key=show_file_paths]'));

  await page.evaluate(()=>{window.fixtureCfg.default_view='waterfall';state.cfg.default_view='waterfall';state.cfg.theme='dark_blue';state.cfg.model_toolbar_locked=true;state.cfg.masonry_card_width=140;state.cfg.masonry_info_mode='fade';state.cfg.masonry_overlay_size='partial';applyUiAppearance();const c=document.createElement('canvas');c.width=140;c.height=210;window.demoCover=c.toDataURL();window.longName='This is a complete model name that should scroll without losing the ending 终点';window.demoRows=Array.from({length:100},(_,i)=>({path:'D:/Demo/'+i+'.pt',name:'local_model_name_'+i+'_very_long_original_filename.safetensors',civitai_name:i===1?'短名':window.longName+' '+i,type:'LORA',base:'Anima',size:1048576}));state.models=fixtureScanRows=demoRows;state.models.forEach(r=>state.coverCache.set(r.path,demoCover));state.mmBaseF=state.mmTypeF='';switchPage('models');mmSetView('masonry');applyMmFilter();});
  const card=page.locator('.ms-card').first();await card.hover({position:{x:50,y:80}});await page.waitForFunction(()=>document.querySelector('.ms-name .name-scroll-text')?.getAnimations().length>0);
  const name=card.locator('.ms-name'),text=name.locator('.name-scroll-text');assert.equal(await text.innerText(),await page.evaluate(()=>longName+' 0'));assert((await name.getAttribute('title')).endsWith('终点 0'));ok('保留完整 C站名称，没有先截断成省略号');
  const anim=await text.evaluate(e=>{const a=e.getAnimations()[0];a.pause();a.currentTime=100;return {x:new DOMMatrixReadOnly(getComputedStyle(e).transform).m41,frames:a.effect.getKeyframes(),duration:a.effect.getTiming().duration};});assert.equal(anim.x,0);assert(anim.frames[1].offset>0);ok('默认每轮开头停顿 350 毫秒');
  const movement=await text.evaluate(e=>{const a=e.getAnimations()[0];a.currentTime=2200;return new DOMMatrixReadOnly(getComputedStyle(e).transform).m41;});assert(movement<0);ok('随后线性缓慢滚动，不移动卡片或列宽');
  assert.equal(await text.evaluate(e=>{const a=e.getAnimations()[0];a.currentTime=a.effect.getTiming().duration+100;return new DOMMatrixReadOnly(getComputedStyle(e).transform).m41;}),0);ok('滚到末尾停顿后回到开头循环');
  assert.equal(await page.locator('.ms-card[data-path="D:/Demo/1.pt"]').locator('.ms-name .name-scroll-text').evaluate(e=>e.getAnimations().length),0);ok('放得下的短名字不播放动画');
  assert.equal(await page.locator('.ms-card').last().locator('.ms-name .name-scroll-text').evaluate(e=>e.getAnimations().filter(a=>a.playState==='running').length),0);ok('屏幕外名称不运行动画');
  const before=await page.locator('#mmMasonryViewport').evaluate(e=>e.scrollTop);await card.locator('.ms-info').hover();await page.mouse.wheel(0,350);await page.waitForFunction(b=>document.querySelector('#mmMasonryViewport').scrollTop>b,before);ok('鼠标在正常悬浮介绍上时滚轮继续滚动模型列表');
  await page.evaluate(()=>document.querySelector('#mmMasonryViewport').scrollTop=0);await page.locator('[data-menu=mmOrganizeMenu]').click();await page.locator('#mmOrganizeMenu [data-proxy=mmMoveTo]').hover();const menuBefore=await page.locator('#mmMasonryViewport').evaluate(e=>e.scrollTop);await page.mouse.wheel(0,280);await page.waitForFunction(b=>document.querySelector('#mmMasonryViewport').scrollTop>b,menuBefore);ok('鼠标停在非滚动的二级菜单上也能滚动模型列表');await page.mouse.click(20,600);
  await page.evaluate(()=>{const menu=document.querySelector('#ctxMenu');menu.innerHTML=Array.from({length:40},(_,i)=>'<button class="ctx-item">测试菜单 '+i+'</button>').join('');Object.assign(menu.style,{display:'block',position:'fixed',left:'400px',top:'100px',height:'140px',maxHeight:'140px'});});await page.locator('#ctxMenu').hover();const listBefore=await page.locator('#mmMasonryViewport').evaluate(e=>e.scrollTop);await page.mouse.wheel(0,150);await page.waitForFunction(()=>document.querySelector('#ctxMenu').scrollTop>0);assert.equal(await page.locator('#mmMasonryViewport').evaluate(e=>e.scrollTop),listBefore);ok('可滚动的长菜单优先滚动自己，不误滚背景');await page.evaluate(()=>document.querySelector('#ctxMenu').style.display='none');
  await page.evaluate(()=>{mmSetView('list');document.querySelector('#mmTableWrap').scrollTop=0;});await page.waitForFunction(()=>!!document.querySelector('.ml-2 .name-scroll-text'));assert((await page.locator('.ml-2 .name-scroll-text').first().innerText()).endsWith('.safetensors'));ok('列表里的本地名字也保留完整末尾');
  await page.evaluate(async()=>{switchPage('dlmanager');fixtureTasks=[{id:'long-task',filename:longName+'.safetensors',status:'pending',progress:0,dest_dir:'D:/Demo'}];await dlRefresh();});await page.setViewportSize({width:1000,height:850});await page.waitForFunction(()=>document.querySelector('#dlTable .name-scroll-text')?.getAnimations().length>0);await page.locator('#dlTable .name-scroll-text').evaluate(e=>e.getAnimations()[0].currentTime=2500);await page.evaluate(()=>dlRefresh());await page.waitForFunction(()=>document.querySelector('#dlTable .name-scroll-text')?.getAnimations().length>0);assert(await page.locator('#dlTable .name-scroll-text').evaluate(e=>e.getAnimations()[0].currentTime>=2500));ok('下载轮询重建行不会反复重置滚动动画');
  await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.querySelector('#dlTable .name-scroll-text')?.getAnimations().length===0);ok('减少动态效果时停用名称动画，完整名称仍可悬停看');
  assert.equal(errors.length,0,JSON.stringify(errors));ok('滚动名称和菜单滚轮无前端异常');console.log('PASS '+passed+' name scroll checks');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
