/* Actual Chromium UI, synthetic models and mocked bridge; no user configuration. */
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(__dirname,'..'),web=path.join(root,'web');
const source=fs.readFileSync(path.join(__dirname,'test_ui_preferences.cjs'),'utf8').replace(/\r\n/g,'\n');
const begin=source.indexOf('await page.addInitScript(')+'await page.addInitScript('.length,end=source.indexOf('\n    });\n    const url',begin)+6,init=eval('('+source.slice(begin,end)+')');
const server=http.createServer((req,res)=>{
 const url=new URL(req.url,'http://localhost'),p=path.resolve(web,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));
 if(!p.startsWith(web+path.sep)){res.writeHead(403).end();return;}
 fs.readFile(p,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':'text/html; charset=utf-8');res.end(b);});
});
let passed=0;function ok(s){console.log('OK '+s);passed++;}
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(init);await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.__ready&&document.querySelector('#settingsForm [data-key=show_file_paths]'));


  await page.evaluate(()=>{Object.assign(fixtureCfg,{default_view:'waterfall',masonry_info_mode:'fade',masonry_overlay_size:'full',name_scroll_speed:70,name_scroll_start_pause:350,name_scroll_end_pause:250});Object.assign(state.cfg,fixtureCfg,{theme:'dark_blue',model_toolbar_locked:true,masonry_card_width:140});document.documentElement.dataset.theme='dark_blue';applyUiAppearance();const c=document.createElement('canvas');c.width=140;c.height=420;const g=c.getContext('2d');g.fillStyle='#699fae';g.fillRect(0,0,140,420);window.optionsCover=c.toDataURL();window.optionsRows=[{path:'D:/Demo/0.pt',name:'original_local_LoRA_filename_that_is_long_and_should_scroll_v1.0.safetensors',civitai_name:'完整的C站模型名称可以利用空间换成多行显示而不提前省略',author:'Demo author',base:'Anima',type:'LORA',ver:'v1.0',size:1048576},{path:'D:/Demo/1.pt',name:'second_local_LoRA_filename_that_should_stay_on_one_line.safetensors',civitai_name:'超长模型名称'.repeat(120),author:'Another author',base:'Krea2',type:'LORA',ver:'v2.0',size:2097152},{path:'D:/Demo/2.pt',name:'unknown_local_LoRA_without_Civitai_information_should_scroll_not_wrap.safetensors',base:'Anima',type:'LORA',size:1048576}];state.models=fixtureScanRows=optionsRows;state.models.forEach(r=>state.coverCache.set(r.path,optionsCover));state.mmBaseF=state.mmTypeF='';switchPage('models');mmSetView('masonry');applyMmFilter();});
  const card=page.locator('.ms-card[data-path="D:/Demo/0.pt"]'),title=card.locator('.ms-name'),sub=page.locator('.ms-card[data-path="D:/Demo/1.pt"] .ms-sub .name-scroll-text');await card.hover();await page.waitForFunction(()=>document.querySelector('.ms-card[data-path="D:/Demo/0.pt"] .ms-sub')?.dataset.localWrap==='true');
  const normal=await title.evaluate(e=>({text:e.textContent,white:getComputedStyle(e).whiteSpace,height:e.clientHeight,scroll:e.scrollHeight,clamp:Number(getComputedStyle(e).webkitLineClamp),animations:e.getAnimations({subtree:true}).length}));assert.equal(normal.text,await page.evaluate(()=>optionsRows[0].civitai_name));assert.equal(normal.white,'normal');assert(normal.clamp>2);assert(normal.scroll<=normal.height+1);assert.equal(normal.animations,0);ok('整卡 C站名称完整换行，能放下就不省略、不滚动');
  const long=page.locator('.ms-card[data-path="D:/Demo/1.pt"] .ms-name');const clipped=await long.evaluate(e=>({height:e.clientHeight,scroll:e.scrollHeight,clamp:Number(getComputedStyle(e).webkitLineClamp),overflow:getComputedStyle(e).overflow,textOverflow:getComputedStyle(e).textOverflow}));assert(clipped.clamp>1&&clipped.scroll>clipped.height);assert.equal(clipped.overflow,'hidden');assert.equal(clipped.textOverflow,'ellipsis');ok('放不下的 C站名称按可用行数省略，仍保留完整原文');
  const local=card.locator('.ms-sub');assert.equal(await local.evaluate(e=>getComputedStyle(e).whiteSpace),'normal');assert.equal(await local.locator('.name-scroll-viewport').count(),0);assert((await local.innerText()).endsWith('.safetensors'));const localbox=await local.boundingBox(),mainbox=await title.boundingBox();assert(localbox.y-(mainbox.y+mainbox.height)<3);ok('大卡片本地文件名完整换行、紧接 C站名，不再浪费中间空白');await page.locator('.ms-card[data-path="D:/Demo/1.pt"]').hover();await page.waitForFunction(()=>document.querySelector('.ms-sub .name-scroll-text')?.getAnimations().length>0);
  const timing=await sub.evaluate(e=>{const a=e.getAnimations()[0],d=a.effect.getTiming().duration,k=a.effect.getKeyframes(),distance=Number(k[2].transform.match(/-([\d.]+)/)[1]);return {start:k[1].offset*d,end:(1-k[2].offset)*d,speed:distance/((d-350-250)/1000),white:getComputedStyle(e.closest('.ms-sub')).whiteSpace};});assert.equal(timing.white,'nowrap');assert(Math.abs(timing.start-350)<1&&Math.abs(timing.end-250)<1&&Math.abs(timing.speed-70)<1);ok('本地 LoRA 文件名单行滚动，默认 70px/s、350/250ms 停顿');const fallback=page.locator('.ms-card[data-path="D:/Demo/2.pt"] .ms-name');assert.equal(await fallback.evaluate(e=>getComputedStyle(e).whiteSpace),'normal');assert.equal(await fallback.locator('.name-scroll-text').count(),0);ok('没有 C站名称时，大卡片本地文件名也完整显示');
  const bounds=await card.boundingBox(),head=await title.boundingBox(),footer=await card.locator('.ms-footer').boundingBox();const area=await card.locator('.ms-titles').boundingBox(),l=await local.boundingBox();assert.equal(await title.evaluate(e=>getComputedStyle(e).textIndent),'0px');assert(Math.abs((head.y-area.y)-(area.y+area.height-l.y-l.height))<4);assert((await card.locator('.ms-titles').boundingBox()).y+ (await card.locator('.ms-titles').boundingBox()).height<=footer.y+2);assert(Math.abs(footer.y+footer.height-(bounds.y+bounds.height))<3);assert.equal(await card.locator('.ms-author').isVisible(),true);assert((await card.locator('.ms-author').innerText()).includes('Demo author'));ok('名称组在上方剩余空间垂直居中，底部资料位置不变');
  await card.hover();await page.waitForFunction(()=>getComputedStyle(document.querySelector('.ms-card[data-path="D:/Demo/0.pt"] .ms-info')).opacity==='1');await page.evaluate(()=>document.querySelector('#mmCount').textContent='3 个');await page.screenshot({path:path.join(root,'docs/screenshots/masonry-full-names.png')});await card.screenshot({path:path.join(root,'.test_tmp/centered-card-preview.png')});
  const previous=clipped.clamp;await page.locator('.ms-card[data-path="D:/Demo/1.pt"] img').evaluate(e=>e.style.height='170px');await page.waitForFunction(n=>Number(getComputedStyle(document.querySelector('.ms-card[data-path="D:/Demo/1.pt"] .ms-name')).webkitLineClamp)<n,previous);ok('卡片尺寸改变后自动重算 C站名称可显示行数');await card.locator('img').evaluate(e=>e.style.height='160px');await page.waitForFunction(()=>document.querySelector('.ms-card[data-path="D:/Demo/0.pt"] .ms-sub').dataset.localWrap==='false');assert.equal(await local.evaluate(e=>getComputedStyle(e).whiteSpace),'nowrap');ok('空间不够时，本地文件名自动恢复单行滚动');await card.locator('img').evaluate(e=>e.style.height='420px');await page.waitForFunction(()=>document.querySelector('.ms-card[data-path="D:/Demo/0.pt"] .ms-sub').dataset.localWrap==='true');assert.equal(await local.locator('.name-scroll-text').count(),0);ok('重新变大时，取消本地名称动画并完整换行');
  await page.evaluate(()=>{state.cfg.masonry_overlay_size='partial';applyUiAppearance();});await page.waitForFunction(()=>document.querySelector('.ms-name .name-scroll-text')?.getAnimations().length>0);assert.equal(await title.evaluate(e=>getComputedStyle(e).whiteSpace),'nowrap');ok('部分覆盖维持单行滚动，不被整卡规则影响');
  await page.evaluate(()=>{state.cfg.masonry_overlay_size='full';applyUiAppearance();});await page.waitForFunction(()=>!document.querySelector('.ms-name[data-civitai-name=true] .name-scroll-viewport'));assert.equal(await title.evaluate(e=>getComputedStyle(e).whiteSpace),'normal');ok('切回整卡恢复多行，移除主名称滚动动画');
  await page.evaluate(()=>{switchPage('settings');buildSettingsForm();showSettingsCategory('appearance');});for(const key of ['name_scroll_speed','name_scroll_start_pause','name_scroll_end_pause'])assert.equal(await page.locator('input[data-key='+key+']').count(),1);assert.equal(await page.locator('input[data-key=name_scroll_speed]').inputValue(),'70');assert.equal(await page.locator('input[data-key=name_scroll_start_pause]').getAttribute('min'),'0');ok('外观设置提供速度与首尾停顿三个独立调整入口');
  for(const [key,value] of [['name_scroll_speed','120'],['name_scroll_start_pause','100'],['name_scroll_end_pause','0']]){const input=page.locator('input[data-key='+key+']');await input.fill(value);await input.dispatchEvent('change');}await page.waitForFunction(()=>fixtureCfg.name_scroll_speed===120&&fixtureCfg.name_scroll_start_pause===100&&fixtureCfg.name_scroll_end_pause===0);ok('修改立即保存，无需额外保存按钮');
  await page.evaluate(()=>switchPage('models'));await page.locator('.ms-card[data-path="D:/Demo/1.pt"]').hover();await page.waitForFunction(()=>{const a=document.querySelector('.ms-sub .name-scroll-text')?.getAnimations()[0];return a&&Math.abs(a.effect.getKeyframes()[1].offset*a.effect.getTiming().duration-100)<1;});const changed=await sub.evaluate(e=>{const a=e.getAnimations()[0],d=a.effect.getTiming().duration,k=a.effect.getKeyframes(),dist=Number(k[2].transform.match(/-([\d.]+)/)[1]);return {speed:dist/((d-100)/1000),end:k[2].offset};});assert(Math.abs(changed.speed-120)<1);assert.equal(changed.end,1);ok('自定义速度即时应用，停顿可设为 0');
  await page.reload();await page.waitForFunction(()=>window.__ready&&document.querySelector('#settingsForm [data-key=show_file_paths]'));assert.deepEqual(await page.evaluate(()=>[state.cfg.name_scroll_speed,state.cfg.name_scroll_start_pause,state.cfg.name_scroll_end_pause]),[120,100,0]);ok('重新打开页面保留三个滚动偏好');
  assert.equal(errors.length,0,JSON.stringify(errors));ok('整卡名称排版与滚动设置无前端异常');console.log('PASS '+passed+' full card name option checks');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
