/* Actual Chromium UI, synthetic models and mocked bridge; no user configuration. */
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(__dirname,'..'),web=path.join(root,'web');
const source=fs.readFileSync(path.join(__dirname,'test_ui_preferences.cjs'),'utf8').replace(/\r\n/g,'\n');
const begin=source.indexOf('await page.addInitScript(')+'await page.addInitScript('.length,end=source.indexOf('\n    });\n    const url',begin)+6,init=eval('('+source.slice(begin,end)+')');
const server=http.createServer((req,res)=>{
 const url=new URL(req.url,'http://localhost'),p=path.resolve(web,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));
 if(!p.startsWith(web+path.sep)){res.writeHead(403).end();return;}
 fs.readFile(p,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':'text/html; charset=utf-8');res.end(b);});
});
let passed=0;function ok(s){console.log('OK '+s);passed++;}
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(init);await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.__ready&&document.querySelector('#settingsForm [data-key=show_file_paths]'));
  await page.evaluate(()=>{window.settingsHaveChanges=()=>false;state.cfg.theme='dark_blue';document.documentElement.dataset.theme='dark_blue';state.cfg.ui_text_size='standard';state.cfg.model_toolbar_locked=true;window.fixtureCfg.default_view='waterfall';state.cfg.default_view='waterfall';applyUiAppearance();switchPage('models');const c=document.createElement('canvas');c.width=280;c.height=400;const g=c.getContext('2d');g.fillStyle='#90b9c7';g.fillRect(0,0,280,400);g.fillStyle='#f7d9a3';g.beginPath();g.arc(205,70,30,0,Math.PI*2);g.fill();g.fillStyle='#284355';g.beginPath();g.moveTo(0,400);g.lineTo(0,220);g.lineTo(100,140);g.lineTo(205,250);g.lineTo(280,130);g.lineTo(280,400);g.fill();window.appearanceCover=c.toDataURL('image/jpeg');window.appearanceModels=[{path:'D:/Demo/models/long-local-name-model-version-details.safetensors',name:'a_very_long_local_filename_with_more_than_two_lines_if_wrapped_v1.2.safetensors',civitai_name:'山川水彩',modelId:1,ver:'v1.2',base:'Anima',type:'LORA',size:150*1048576},{path:'D:/Demo/models/second.safetensors',name:'second.safetensors',civitai_name:'星夜风格',modelId:2,ver:'v2',base:'Krea2',type:'LORA',size:200*1048576}];state.models=window.appearanceModels;window.fixtureScanRows=window.appearanceModels;state.models.forEach(r=>state.coverCache.set(r.path,window.appearanceCover));mmSetView('masonry');state.mmBaseF='';state.mmTypeF='';applyMmFilter();document.querySelector('.content').scrollTop=0;});
  const card=page.locator('.ms-card').first(),info=card.locator('.ms-info'),sub=card.locator('.ms-sub');assert.equal(await sub.evaluate(e=>getComputedStyle(e).whiteSpace),'nowrap');assert((await sub.boundingBox()).height<24);assert.equal(await info.evaluate(e=>getComputedStyle(e).position),'static');ok('默认保留常驻介绍，本地名字只占一行');
  for(const mode of ['slide','fade']){
   await page.evaluate(mode=>{window.fixtureCfg.masonry_info_mode=state.cfg.masonry_info_mode=mode;window.fixtureCfg.masonry_overlay_size=state.cfg.masonry_overlay_size='partial';applyUiAppearance();},mode);await page.mouse.move(20,20);await page.waitForTimeout(250);assert.equal(await info.evaluate(e=>getComputedStyle(e).position),'absolute');assert.equal(await info.evaluate(e=>getComputedStyle(e).opacity),'0');const height=(await card.boundingBox()).height;await card.hover({position:{x:40,y:60}});await page.waitForFunction(()=>{const c=document.querySelector('.ms-card');return c?.matches(':hover')&&getComputedStyle(c.querySelector('.ms-info')).opacity==='1';});assert.equal(await info.evaluate(e=>getComputedStyle(e).opacity),'1');assert(Math.abs((await card.boundingBox()).height-height)<1);const overlay=await info.boundingBox(),bounds=await card.boundingBox();assert(overlay.height<bounds.height-50);ok(mode+' 模式悬停显示，离开隐藏且不挤动卡片');
  }
  await page.evaluate(()=>{window.fixtureCfg.masonry_overlay_size=state.cfg.masonry_overlay_size='full';applyUiAppearance();});await card.hover();await page.waitForTimeout(200);const full=await info.boundingBox(),bounds=await card.boundingBox();assert(Math.abs(full.height-bounds.height)<4);ok('整卡片覆盖范围生效');const name=await card.locator('.ms-name').boundingBox();assert(name.y-bounds.y>=0);const footer=await card.locator('.ms-footer').boundingBox();assert(Math.abs(footer.y+footer.height-(bounds.y+bounds.height))<4);ok('整卡片双名称在剩余空间居中，辅助信息置底');const type=await info.evaluate(e=>({name:parseFloat(getComputedStyle(e.querySelector('.ms-name')).fontSize),sub:parseFloat(getComputedStyle(e.querySelector('.ms-sub')).fontSize)}));assert.equal(type.name,15);assert.equal(type.sub,13);ok('悬浮层主名称 15px、辅助信息 13px，不改变全局字号');await page.evaluate(()=>{state.cfg.ui_text_size='huge';applyUiAppearance();});const large=await info.evaluate(e=>({name:parseFloat(getComputedStyle(e.querySelector('.ms-name')).fontSize),sub:parseFloat(getComputedStyle(e.querySelector('.ms-sub')).fontSize)}));assert(large.name>15&&large.sub>13);await page.evaluate(()=>{state.cfg.ui_text_size='standard';applyUiAppearance();});ok('悬浮文字继续响应用户全局字号设置');
  await card.locator('.ms-check').click();assert.equal(await card.evaluate(e=>e.classList.contains('checked')),true);await card.locator('.ms-check').click();ok('整卡片悬浮介绍不遮住独立勾选');
  const smallCard=page.locator('.ms-card').nth(1);await smallCard.locator('img').evaluate(e=>{e.style.height='50px';e.style.minHeight='0';});await smallCard.hover();await page.waitForTimeout(240);const compact=await smallCard.locator('.ms-info').evaluate(e=>({overflow:getComputedStyle(e).overflowY,scroll:e.scrollHeight,client:e.clientHeight}));assert.equal(compact.overflow,'auto');assert(compact.scroll>compact.client);await smallCard.locator('.ms-info').evaluate(e=>e.scrollTop=e.scrollHeight);assert(await smallCard.locator('.ms-size').evaluate(e=>{const a=e.getBoundingClientRect(),b=e.parentElement.getBoundingClientRect();return a.bottom<=b.bottom+1;}));ok('短横图卡片的大号介绍可滚动查看，末尾信息不截断');await smallCard.locator('img').evaluate(e=>{e.style.height='';e.style.minHeight='';});await card.hover();await page.waitForTimeout(200);
  await page.screenshot({path:path.join(root,'docs/screenshots/masonry-hover-dark.png')});
  await page.evaluate(()=>{state.cfg.theme='light';document.documentElement.dataset.theme='light';applyUiAppearance();});await card.hover();await page.waitForTimeout(220);const light=await info.evaluate(e=>({bg:getComputedStyle(e).backgroundColor,color:getComputedStyle(e).color}));assert(light.bg.includes('255, 255, 255'));assert.equal(light.color,'rgb(22, 32, 45)');await page.screenshot({path:path.join(root,'docs/screenshots/masonry-hover-light.png')});ok('亮色主题为半透明亮底和深色文字');
  await page.mouse.move(20,20);await card.focus();await page.waitForTimeout(250);assert.equal(await info.evaluate(e=>getComputedStyle(e).opacity),'1');ok('键盘聚焦也可显示卡片介绍');
  await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await info.evaluate(e=>getComputedStyle(e).transitionDuration),'0s');ok('减少动态效果时不播放过渡动画');await page.emulateMedia({reducedMotion:'no-preference'});
  await page.evaluate(()=>{state.cfg.theme='dark_blue';document.documentElement.dataset.theme='dark_blue';applyUiAppearance();});await page.locator('[data-menu=mmOrganizeMenu]').click();await page.locator('[data-proxy=mmMoveTo]').hover();await page.waitForTimeout(150);const tip=page.locator('.tip-float');assert.equal(await tip.isVisible(),true);const layers=await page.evaluate(()=>({tip:Number(getComputedStyle(document.querySelector('.tip-float')).zIndex),menu:Number(getComputedStyle(document.querySelector('#mmOrganizeMenu')).zIndex)}));assert(layers.tip>layers.menu);assert.equal(await tip.evaluate(e=>getComputedStyle(e).pointerEvents),'none');const tipbox=await tip.boundingBox();assert(tipbox.x>=0&&tipbox.y>=0&&tipbox.x+tipbox.width<=1920&&tipbox.y+tipbox.height<=1080);ok('二级菜单说明位于菜单之上，不挡点击、不越界');await page.keyboard.press('Escape');await page.mouse.click(30,30);
  await page.evaluate(()=>{switchPage('dlmanager');window.fixtureTasks=[{id:'demo',filename:'demo.pt',status:'pending',progress:0,dest_dir:'D:/Demo'}];});await page.evaluate(()=>dlRefresh());await page.evaluate(()=>{document.documentElement.dataset.nativeMaterial='true';document.documentElement.dataset.zebra='true';});const mica=await page.locator('#dlTable').evaluate(t=>({wrapper:getComputedStyle(t.parentElement).backgroundColor,row:getComputedStyle(t.querySelector('tbody tr')).backgroundColor}));assert.equal(mica.wrapper,'rgba(0, 0, 0, 0)');assert(!mica.row.endsWith(', 1)')&&!mica.row.startsWith('rgb('));ok('原生材质开启时下载表格与外壳透出 Mica');
  await page.evaluate(()=>{document.documentElement.dataset.nativeMaterial='false';});assert.notEqual(await page.locator('#dlTable').evaluate(t=>getComputedStyle(t.parentElement).backgroundColor),'rgba(0, 0, 0, 0)');ok('普通窗口/浏览器模式仍保留不透明背景');
  await page.evaluate(async()=>{switchPage('updates');state.models=window.appearanceModels;state.mmUpdItems={};state.updQ='';state.updState='';state.updBase='';await renderUpdatesPage();});assert((await page.locator('#updCount').innerText()).includes('共 2 个'));assert.equal(await page.locator('#updStat').innerText(),'共 2 个模型');ok('没有旧缓存时更新页总数仍与模型库一致');
  await page.setViewportSize({width:2560,height:1440});await page.waitForTimeout(120);const wide=await page.locator('#updTable').evaluate(t=>({table:t.getBoundingClientRect().width,wrap:t.parentElement.getBoundingClientRect().width,overflow:getComputedStyle(t.parentElement).overflowX}));assert(Math.abs(wide.table-wide.wrap)<4);assert.equal(wide.overflow,'hidden');ok('更新表格在宽屏铺满，消除右侧空白');
  await page.setViewportSize({width:1000,height:850});await page.waitForTimeout(120);assert.equal(await page.locator('#updTable').evaluate(t=>getComputedStyle(t.parentElement).overflowX),'auto');ok('更新表格小窗保留真正的横向滚动');
  await page.evaluate(()=>{switchPage('settings');buildSettingsForm();showSettingsCategory('appearance');});assert.equal(await page.locator('[data-key=masonry_info_mode] option').count(),3);assert.equal(await page.locator('[data-key=masonry_overlay_size] option').count(),2);ok('设置中可选三种介绍模式与两种覆盖范围');await page.locator('select[data-key=masonry_info_mode]').selectOption('slide');await page.locator('select[data-key=masonry_overlay_size]').selectOption('full');await page.waitForFunction(()=>fixtureCfg.masonry_info_mode==='slide'&&fixtureCfg.masonry_overlay_size==='full');assert.equal(await page.evaluate(()=>document.documentElement.dataset.masonryInfo),'slide');ok('真实设置选择立即应用并自动保存');await page.reload();await page.waitForFunction(()=>window.__ready&&document.querySelector('#settingsForm [data-key=show_file_paths]'));assert.deepEqual(await page.evaluate(()=>[state.cfg.masonry_info_mode,state.cfg.masonry_overlay_size,document.documentElement.dataset.masonryInfo]),['slide','full','slide']);ok('重新打开页面保留悬浮方式和覆盖范围');
  assert.equal(errors.length,0,JSON.stringify(errors));ok('全部新外观功能无前端异常');console.log('PASS '+passed+' masonry appearance checks');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
