/* Actual Chromium UI, synthetic models and mocked bridge; no user configuration. */
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(__dirname,'..'),web=path.join(root,'web');
const source=fs.readFileSync(path.join(__dirname,'test_ui_preferences.cjs'),'utf8').replace(/\r\n/g,'\n');
const begin=source.indexOf('await page.addInitScript(')+'await page.addInitScript('.length,end=source.indexOf('\n    });\n    const url',begin)+6,init=eval('('+source.slice(begin,end)+')');
const server=http.createServer((req,res)=>{
 const url=new URL(req.url,'http://localhost'),p=path.resolve(web,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));
 if(!p.startsWith(web+path.sep)){res.writeHead(403).end();return;}
 fs.readFile(p,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':'text/html; charset=utf-8');res.end(b);});
});
let passed=0;function ok(s){console.log('OK '+s);passed++;}
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(init);await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.__ready);
  await page.evaluate(()=>{
   window.settingsHaveChanges=()=>false;switchPage('models');state.cfg.model_toolbar_locked=true;state.cfg.theme='dark_blue';document.documentElement.dataset.theme='dark_blue';applyUiAppearance();
   window.safetyModels=[{path:'D:/Demo/models/anima.pt',name:'Anima.pt',base:'Anima',type:'Checkpoint',type_filter:'Checkpoint'},{path:'D:/Demo/models/krea.pt',name:'Krea.pt',base:'Krea2',type:'Checkpoint',type_filter:'Checkpoint'},{path:'D:/Demo/models/lora.pt',name:'style.pt',base:'Anima',type:'LORA',type_filter:'LORA'}];state.models=window.safetyModels;window.fixtureScanRows=window.safetyModels;state.mmView='list';state.mmBaseF='';state.mmTypeF='';state.mmChecked.clear();state.mmSel.clear();$('#mmFilter').value='';applyMmFilter();
   window.moveCalls=[];window.scanCalls=0;window.mmScan=()=>{window.scanCalls++;};window.pickFolderModal=async()=> 'D:/Demo/target';window.confirmBoxRaw=async()=>true;
   const original=api.call.bind(api);api.call=async(method,...args)=>{if(method==='move_file_to'){window.moveCalls.push(args);return {ok:true,path:args[0],msg:'fixture move'};}if(method==='get_mm_progress')return {running:false};return original(method,...args);};
  });
  await page.locator('#mmBaseF').selectOption('Anima');await page.locator('#mmSelAll').click();assert.equal(await page.evaluate(()=>state.mmChecked.size),2);await page.locator('#mmBaseF').selectOption('Krea2');assert.equal(await page.evaluate(()=>state.mmChecked.size),0);assert.equal(await page.evaluate(()=>state.mmSel.size),0);ok('切换 Anima → Krea2 清掉全部不可见勾选');
  await page.locator('#mmSelAll').click();await page.evaluate(()=>state.mmChecked.add(window.safetyModels[0].path));assert.deepEqual(await page.evaluate(()=>mmCheckedPaths()),['D:/Demo/models/krea.pt']);ok('批量动作再次校验可见范围，不信任隐藏勾选');
  await page.locator('[data-menu=mmOrganizeMenu]').click();await page.locator('[data-proxy=mmMoveTo]').click();await page.waitForFunction(()=>window.moveCalls.length===1);assert.equal(await page.evaluate(()=>window.moveCalls[0][0]),'D:/Demo/models/krea.pt');ok('批量移动只移动当前可见 Krea2，不夹带 Anima');
  await page.locator('#mmBaseF').selectOption('');await page.evaluate(()=>state.mmChecked.add(window.safetyModels[0].path));await page.locator('#mmTypeF').selectOption('LORA');assert.equal(await page.evaluate(()=>state.mmChecked.size),0);ok('类型过滤也清掉隐藏选择');
  await page.locator('#mmTypeF').selectOption('');await page.evaluate(()=>{state.mmChecked.add(window.safetyModels[0].path);state.mmChecked.add(window.safetyModels[1].path);});await page.locator('#mmFilter').fill('Krea');await page.waitForTimeout(250);assert.deepEqual(await page.evaluate(()=>Array.from(state.mmChecked)),['D:/Demo/models/krea.pt']);ok('关键词过滤清掉不可见选择');
  assert.equal(await page.locator('#mmFilterClear').evaluate(e=>e.parentElement.classList.contains('mm-search-field')),true);await page.locator('#mmFilterClear').click();assert.equal(await page.locator('#mmFilter').inputValue(),'');assert.equal(await page.evaluate(()=>state.mmChecked.size),1);assert.equal(await page.evaluate(()=>state.mmBaseF),'');ok('搜索框内 × 只清搜索，不清现有勾选');
  await page.locator('#mmSelNone').click();assert.equal(await page.evaluate(()=>state.mmChecked.size),0);ok('清除勾选仍单独生效');
  await page.evaluate(()=>{state.mmChecked.add(window.safetyModels[0].path);state.mmChecked.add(window.safetyModels[1].path);showModelContextMenu({preventDefault(){},clientX:450,clientY:400},window.safetyModels[0]);});assert.equal(await page.locator('#ctxMenu [data-act=move]').count(),1);assert.equal(await page.locator('#ctxMenu [data-act=move]').evaluate(e=>e.parentElement.id==='ctxMenu'),true);await page.locator('#ctxMenu [data-act=move]').click();await page.waitForFunction(()=>window.moveCalls.length===2);assert.equal(await page.evaluate(()=>window.moveCalls.at(-1)[0]),'D:/Demo/models/anima.pt');ok('一级右键单模型移动只提交右键模型，不包含其它勾选');
  assert((await page.locator('[data-proxy=mmOrganize]').getAttribute('data-tip')).includes('不是刷新'));assert((await page.locator('#mmMoveTo').getAttribute('data-tip')).includes('隐藏模型'));ok('整理与移动均有具体悬浮用途说明');
  // A background rename must finish before scanning.
  await page.evaluate(()=>{
   window.renameRunning=true;window.renameScans=0;window.renameStarted=false;window.pollMmScan=()=>{};
   const original=api.call.bind(api);api.call=async(method,...args)=>{if(method==='mm_rename_preview')return {items:[{old:'Krea.pt',new:'Krea-v1.pt',same:false}]};if(method==='mm_rename'){window.renameStarted=true;return {started:true};}if(method==='get_mm_progress')return {running:window.renameRunning,total:1,done:window.renameRunning?0:1,msg:'fixture rename'};if(method==='scan_models'){window.renameScans++;return {started:true};}return original(method,...args);};mmRenamePreview('rename_c',['D:/Demo/models/krea.pt']);
  });await page.locator('#rpApply').click();await page.waitForFunction(()=>window.renameStarted);await page.waitForTimeout(900);assert.equal(await page.evaluate(()=>window.renameScans),0);await page.evaluate(()=>window.renameRunning=false);await page.waitForFunction(()=>window.renameScans===1);ok('批量改名等待后台完成，杜绝提前刷新旧路径');
  // Queue hover calls HQ API rather than scaling the small icon.
  await page.evaluate(()=>{switchPage('dlmanager');const c=document.createElement('canvas');c.width=1024;c.height=1024;c.getContext('2d').fillRect(0,0,1024,1024);window.hqCover=c.toDataURL('image/jpeg').split(',')[1];window.hqCalls=[];const original=api.call.bind(api);api.call=async(method,...args)=>{if(method==='get_task_hover_cover'){window.hqCalls.push(args[0]);return window.hqCover;}return original(method,...args);};const cell=document.createElement('tr');cell.dataset.taskId='hq-task';const td=document.createElement('td');const img=new Image();img.className='hq-fixture';img.src='data:image/jpeg;base64,'+window.hqCover;img.style.cssText='width:32px;height:32px';td.appendChild(img);cell.appendChild(td);$('#dlTable tbody').prepend(cell);});await page.locator('.hq-fixture').hover();await page.waitForFunction(()=>window.hqCalls.includes('hq-task'));await page.waitForFunction(()=>document.querySelector('.cover-hover-preview img')?.naturalWidth===1024);ok('下载任务悬浮窗独立读取高清源');

  await page.mouse.move(20,20);await page.setViewportSize({width:2560,height:1440});await page.evaluate(()=>{const table=$('#dlTable');table.dataset.hasErrors='false';});await page.waitForTimeout(150);
  const wide=await page.evaluate(()=>{const t=$('#dlTable'),w=t.parentElement;return {table:t.getBoundingClientRect().width,wrap:w.getBoundingClientRect().width,overflow:getComputedStyle(w).overflowX};});assert(Math.abs(wide.table-wide.wrap)<4,JSON.stringify(wide));assert.equal(wide.overflow,'hidden');ok('宽屏下载表格铺满，无右侧空白和多余横条');
  await page.setViewportSize({width:1000,height:850});await page.waitForTimeout(150);assert.equal(await page.locator('#dlTable').evaluate(t=>getComputedStyle(t.parentElement).overflowX),'auto');ok('窄屏保留真实横向滚动，不截断可调列宽');
  await page.evaluate(()=>{window.historyThumbCalls=0;window.fixtureHistory=[{id:'stable-history',filename:'done.pt',status:'done',dest_dir:'D:/Demo/models',cached_thumb:true,thumb_revision:1}];const original=api.call.bind(api);api.call=async(method,...args)=>{if(method==='get_history_thumbnail'&&args[0]==='stable-history'){window.historyThumbCalls++;return window.hqCover;}return original(method,...args);};});await page.locator('#dlHistoryTab').click();await page.waitForFunction(()=>!!document.querySelector('[data-history-thumb="stable-history"] img'));const cell=await page.locator('[data-history-thumb="stable-history"] img').elementHandle();await page.evaluate(async()=>{await refreshDownloadHistory();await refreshDownloadHistory();});assert.equal(await page.evaluate(()=>window.historyThumbCalls),1);assert.equal(await cell.evaluate(e=>e.isConnected),true);ok('历史轮询不重建同一封面，也不重复读取缩略图');
  await page.evaluate(()=>{window.fixtureHistory[0].thumb_revision=2;});await page.evaluate(()=>refreshDownloadHistory());await page.waitForFunction(()=>window.historyThumbCalls===2);ok('封面实际变化时按修订号重新读取');
  await page.locator('#dlQueueTab').click();await page.evaluate(()=>{window.fixtureTasks=[{id:'done',filename:'done.pt',status:'done',dest_dir:'D:/Demo',progress:100,downloaded:100,total:100},{id:'active',filename:'active.pt',status:'downloading',dest_dir:'D:/Demo',progress:50,downloaded:50,total:100}];});await page.evaluate(()=>dlRefresh());await page.locator('#dlRemoveCompleted').click();const removed=await page.evaluate(()=>window.fixtureCalls.filter(c=>c.method==='dl_action'&&c.args[0]==='remove_completed').at(-1));assert.equal(removed.args[2],null);ok('移除已完成为独立操作，不误用全部移除');
  await page.evaluate(()=>dlRefresh());
  const row=page.locator('#dlTable tr[data-task-id=active]');const check=await row.locator('.dl-task-check').boundingBox(),handle=await row.locator('.dl-drag-handle').boundingBox(),rowBox=await row.boundingBox();assert(check.width>=20&&handle.width>=28);assert(Math.abs(check.y+check.height/2-rowBox.y-rowBox.height/2)<2);assert(Math.abs(handle.y+handle.height/2-rowBox.y-rowBox.height/2)<2);ok('下载勾选框与排序手柄放大且上下居中');
  await page.setViewportSize({width:1920,height:1080});await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=320;c.height=400;const g=c.getContext('2d');g.fillStyle='#90b9c7';g.fillRect(0,0,320,400);g.fillStyle='#f7d9a3';g.beginPath();g.arc(235,70,32,0,Math.PI*2);g.fill();g.fillStyle='#284355';g.beginPath();g.moveTo(0,400);g.lineTo(0,220);g.lineTo(100,150);g.lineTo(230,240);g.lineTo(320,130);g.lineTo(320,400);g.fill();const b=c.toDataURL('image/jpeg').split(',')[1];state.dlThumbs.done=b;state.dlThumbs.active=b;await dlRefresh();document.querySelector('.content').scrollTop=0;});await page.screenshot({path:path.join(root,'docs/screenshots/download-queue-v2617.png')});
  assert.equal(errors.length,0,JSON.stringify(errors));ok('新安全交互无前端异常');console.log('PASS '+passed+' operation safety checks');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
